version: '3.2'
services:
  crm-db:
    image: postgres:15-alpine
    container_name: CRM_DB
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./db/:/var/lib/postgresql/data

  crm:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c "./manage.py makemigrations &&
            ./manage.py migrate &&
             uvicorn crm_project.asgi:application --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./files/:/crm_project/files
    depends_on:
      - crm-db
