# Generated by Django 5.0.2 on 2024-03-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goods',
            new_name='Products',
        ),
    ]
