# Generated by Django 5.0.2 on 2024-03-03 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leads')),
            ],
            options={
                'verbose_name': 'активный клиент',
                'verbose_name_plural': 'активные клиенты',
                'ordering': ('lead',),
            },
        ),
    ]
