# Generated by Django 5.0.2 on 2024-03-05 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('customers', '0001_initial'),
        ('leads', '0003_alter_leads_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='contracts.contracts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leads'),
        ),
    ]
