# Generated by Django 5.0.2 on 2024-03-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('customers', '0003_alter_customers_contract'),
        ('leads', '0005_leads_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('lead', 'contract')},
        ),
    ]
