# Generated by Django 5.0.2 on 2024-03-09 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customers_unique_together'),
        ('leads', '0007_alter_leads_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='leads.leads'),
        ),
    ]
