# Generated by Django 5.0.2 on 2024-03-18 07:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advertise", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Leads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=200, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=200, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=200, verbose_name="Отчество"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Некорректный ввод. формат: '+999999999' от 9 до 15 цифр.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "advertising",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="advertise.advertise",
                        verbose_name="кампания",
                    ),
                ),
            ],
            options={
                "verbose_name": "потенциальный клиент",
                "verbose_name_plural": "потенциальные клиенты",
                "ordering": ("last_name",),
            },
        ),
    ]
