# Generated by Django 5.0.2 on 2024-03-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_remove_advertise_product_advertise_product'),
        ('leads', '0002_leads_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='advertising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='advertise.advertise', verbose_name='кампания'),
        ),
    ]
