# Generated by Django 5.0.2 on 2024-03-08 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_alter_advertise_name'),
        ('leads', '0003_alter_leads_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='middle_name',
            field=models.CharField(default='', max_length=200, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leads',
            name='advertising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertise.advertise', verbose_name='кампания'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Некорректный ввод. формат: '+999999999' от 9 до 15 цифр.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
