# Generated by Django 5.0.2 on 2024-03-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_alter_advertise_name'),
        ('leads', '0005_leads_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='advertising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='advertise.advertise', verbose_name='кампания'),
        ),
    ]
