# Generated by Django 5.0.2 on 2024-03-09 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0006_alter_advertise_name'),
        ('leads', '0006_alter_leads_advertising'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='advertising',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='advertise.advertise', verbose_name='кампания'),
        ),
    ]
