# Generated by Django 5.0.2 on 2024-03-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertise',
            name='product',
        ),
        migrations.AddField(
            model_name='advertise',
            name='product',
            field=models.ManyToManyField(related_name='services', to='products.products', verbose_name='Услуга'),
        ),
    ]
