# Generated by Django 5.0.2 on 2024-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0003_remove_advertise_product_advertise_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='name',
            field=models.TextField(max_length=1000, verbose_name='Кампания'),
        ),
    ]
