# Generated by Django 5.0.2 on 2024-03-09 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0004_alter_advertise_name'),
        ('products', '0002_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='products.products', verbose_name='Услуга'),
        ),
    ]
