# Generated by Django 5.0.2 on 2024-03-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertise', '0005_alter_advertise_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Кампания'),
        ),
    ]
